name: Update Container

on:
  push:
    branches:
      - develop

env:
  CONTAINER: ghcr.io/deepmodeling/abacus-development-kit:gnu

jobs:
  build_container_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.PAT }}
      - uses: docker/build-push-action@v2
        with:
          tags: ${{ env.CONTAINER }}
          cache-from: type=registry,ref=${{ env.CONTAINER }}
          push: true
