name: Container

on:
  push:
    branches:
      - develop
      - reconstruction

env:
  CONTAINER: ${{ github.repository }}:gnu

jobs:
  build_container_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["gnu","intel"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          tags: ${{ github.repository }}:${{matrix.dockerfile}}
          file: Dockerfile.${{matrix.dockerfile}}
          cache-from: type=registry,ref=${{ github.repository }}:${{matrix.dockerfile}}
          cache-to: type=inline
          push: true
