name: Test

on:
  push:
    branches:
      - develop
      - reconstruction

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/abacus-development-kit:gnu
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.OWNER }}
          password: ${{ secrets.PAT }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -B build -DBUILD_TESTING=ON
          cmake --build build -j4
          cmake --install build
          ctest --test-dir build --verbose
