name: Test

on:
  push:
    branches:
      - develop
      - reconstruction

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/abacus-development-kit:gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON
          cmake --build build -j4
          cmake --install build
      - name: Test
        run: |
          ctest --test-dir build --verbose
