name: Test

on:
  push:
    branches:
      - develop
      - reconstruction

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ["gnu","intel","cuda"]
    container: ghcr.io/${{ github.repository_owner }}/abacus-development-kit:${{ matrix.dockerfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON
          cmake --build build -j4
          cmake --install build
