name: Test

on:
  push:
    branches:
      - develop
      - reconstruction

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - tag: gnu
          build_args: ""
        - tag: gnu
          build_args: "-DENABLE_DEEPKS=1 -DENABLE_LIBXC=1"
        - tag: intel
          build_args: ""
        - tag: cuda
          build_args: "-DUSE_CUDA=1"

    container: ghcr.io/${{ github.repository_owner }}/abacus-development-kit:${{ matrix.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON ${{ matrix.build_args }}
          cmake --build build -j4
          cmake --install build
