name: Test

on:
  pull_request:
    branches:
      - develop
      - reconstruction

env:
  CONTAINER: ghcr.io/deepmodeling/abacus-development-kit:gnu

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ env.CONTAINER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -B build
          cmake --build build -j4
          cmake --install build
          ctest --test-dir build --verbose
